spring:
  application:
    name: ms-pedidos
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000

server:
  port: 8090

inventario:
  base-url: http://localhost:8091

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

resilience4j:
  circuitbreaker:
    instances:
      inventario:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
