apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-inventario
  template:
    metadata:
      labels:
        app: ms-inventario
    spec:
      containers:
      - name: ms-inventario
        image: ms-inventario:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8091
